In [82]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/janatahack-crosssell-prediction/train.csv
/kaggle/input/janatahack-crosssell-prediction/sample_submission_iA3afxn.csv
/kaggle/input/janatahack-crosssell-prediction/test.csv


# **Data Stats **


In [83]:
#import seaborn as sns
#train[train['Gender']=='Male']['Response'].sum()
#train[train['Gender']=='Female']['Response'].sum()
#col=['Gender','Response']
#sns.pairplot(train[col])
#col=train.columns
#print(col)
#col=[ 'Gender', 'Age', 'Driving_License', 'Region_Code',
#       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
#       'Policy_Sales_Channel', 'Vintage', 'Response']

#sns.pairplot(train[col])
#col=['Response','Vintage']

#sns.pairplot(train[col])
#import matplotlib.pyplot as plt 
#var = 'Vehicle_Age'
#data = pd.concat([train['Response'], train[var]], axis=1)
#data.plot.scatter(x=var, y='Vehicle_Age', ylim=(0,1));

#train[train['Response']==0]['Vehicle_Age'].unique()

#train[train['Response']==1]['Vehicle_Age'].unique()

#print(len(train[train['Previously_Insured']==1][train['Response']==0]))
#print(len(train[train['Previously_Insured']==1]))
#col=['Annual_Premium','Response']
#sns.distplot(train[col])



In [84]:
#print("The number of classes before fit {}".format(Counter(target)))
#print("The number of classes after fit {}".format(Counter(y_train_ns)))

In [85]:
#X_train_ns['Response'].sum()
 
#target=X_train_ns['Response']
#X_train_ns=X_train_ns.drop(['Response'],axis=1)

In [86]:
'''
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8)
X_train_ns,y_train_ns=ns.fit_sample(X_train_ns,target)
print("The number of classes before fit {}".format(Counter(target)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

'''

'\nfrom imblearn.under_sampling import NearMiss\nns=NearMiss(0.8)\nX_train_ns,y_train_ns=ns.fit_sample(X_train_ns,target)\nprint("The number of classes before fit {}".format(Counter(target)))\nprint("The number of classes after fit {}".format(Counter(y_train_ns)))\n\n'

In [87]:
#X_train_ns

In [88]:
'''
print(len(train[train['Driving_License']==1][target==0]))
print(len(train[train['Driving_License']==0][target==0]))
print(len(train[train['Driving_License']==1][target==1]))
print(len(train[train['Driving_License']==0][target==1]))

print(len(train[train['Previously_Insured']==1][target==0]))
print(len(train[train['Previously_Insured']==0][target==0]))
print(len(train[train['Previously_Insured']==1][target==1]))
print(len(train[train['Previously_Insured']==0][target==1]))

print(len(train[train['Gender']==1][target==0]))
print(len(train[train['Gender']==0][target==0]))
print(len(train[train['Gender']==1][target==1]))
print(len(train[train['Gender']==0][target==1]))

'''

"\nprint(len(train[train['Driving_License']==1][target==0]))\nprint(len(train[train['Driving_License']==0][target==0]))\nprint(len(train[train['Driving_License']==1][target==1]))\nprint(len(train[train['Driving_License']==0][target==1]))\n\nprint(len(train[train['Previously_Insured']==1][target==0]))\nprint(len(train[train['Previously_Insured']==0][target==0]))\nprint(len(train[train['Previously_Insured']==1][target==1]))\nprint(len(train[train['Previously_Insured']==0][target==1]))\n\nprint(len(train[train['Gender']==1][target==0]))\nprint(len(train[train['Gender']==0][target==0]))\nprint(len(train[train['Gender']==1][target==1]))\nprint(len(train[train['Gender']==0][target==1]))\n\n"

In [89]:
#target=pd.concat([target,train['Driving_License']],axis=1)


In [90]:
#from imblearn.under_sampling import NearMiss
#nm=NearMiss()
#train_new,target_new=nm.fit_sample(train,target)

# **Python Code **

In [91]:
train=pd.read_csv('../input/janatahack-crosssell-prediction/train.csv')
test=pd.read_csv('../input/janatahack-crosssell-prediction/test.csv')

In [92]:

target=train['Response']
train=train.drop(['Response','id'],axis=1)
a={'Male':0,'Female':1}
train['Gender']=train['Gender'].map(a)
a={'> 2 Years':0, '1-2 Year':2, '< 1 Year':1}
train['Vehicle_Age']=train['Vehicle_Age'].map(a)
a={'Yes':1,'No':0}
train['Vehicle_Damage']=train['Vehicle_Damage'].map(a)



a={'Male':0,'Female':1}
test['Gender']=test['Gender'].map(a)
a={'> 2 Years':0, '1-2 Year':2, '< 1 Year':1}
test['Vehicle_Age']=test['Vehicle_Age'].map(a)
a={'Yes':1,'No':0}
test['Vehicle_Damage']=test['Vehicle_Damage'].map(a)

ids=test['id']
test=test.drop(['id'],axis=1)

# **Oversampling**

In [93]:

from imblearn.over_sampling import RandomOverSampler
from collections import Counter

os=RandomOverSampler(0.75)
train_new,target_new=os.fit_sample(train,target)


/opt/conda/lib/python3.7/site-packages/imblearn/utils/_validation.py:638: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


In [94]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(train_new,target_new,test_size=0.2,random_state=3)

In [96]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)



NameError: name 'classifier' is not defined

In [97]:
y_pred=rfc.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[60431  6382]
 [  338 49889]]
0.9425837320574163
              precision    recall  f1-score   support

           0       0.99      0.90      0.95     66813
           1       0.89      0.99      0.94     50227

    accuracy                           0.94    117040
   macro avg       0.94      0.95      0.94    117040
weighted avg       0.95      0.94      0.94    117040



# **SMOTETOMEK**

In [99]:
from imblearn.combine import SMOTETomek
os=SMOTETomek(0.75)
X_train_ns,y_train_ns=os.fit_sample(train,target)
#print("The number of classes before fit {}".format(Counter(y_train)))
#print("The number of classes after fit {}".format(Counter(y_train_ns)))

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

rfc=RandomForestClassifier()
rfc.fit(X_train_ns,y_train_ns)


#from xgboost import XGBClassifier
#from sklearn.metrics import accuracy_score
#lr=XGBClassifier()
#lr.fit(X_train,y_train)


RandomForestClassifier()

In [100]:
y_pred=rfc.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[66358   455]
 [ 1066 49161]]
0.9870044429254956
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     66813
           1       0.99      0.98      0.98     50227

    accuracy                           0.99    117040
   macro avg       0.99      0.99      0.99    117040
weighted avg       0.99      0.99      0.99    117040



In [101]:
roc_auc_score(y_test,pred)

0.8099630764053645

In [103]:
pr=rfc.predict(test)



output = pd.DataFrame({'id': ids, 'Response': pr})
output.to_csv('my_submission2.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!


In [69]:
from sklearn.metrics import roc_auc_score
ns_auc = roc_auc_score(y_test,pred)
ns_auc

0.8096282976762755

In [70]:
from sklearn.metrics import confusion_matrix
ns_auc = confusion_matrix(y_test,pred)

In [71]:
ns_auc

array([[48237, 18576],
       [ 5159, 45068]])

In [60]:
#true positive rate or sensitivity or recall
ns_auc[0][0] / (ns_auc[0][0] + ns_auc[1][0])

0.8779092650415891

In [62]:
#true negatice rate or inverted specificity
ns_auc[0][1] / (ns_auc[0][1] + ns_auc[1][1])

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in long_scalars
  """Entry point for launching an IPython kernel.


nan

In [66]:
print("no with labels as 0",len(target)-target.sum())
print("no wth label as 1",target.sum())

no with labels as 0 334399
no wth label as 1 46710


In [68]:
target.sum()/(len(target)-target.sum())

0.13968343206767964