In [1]:
import pandas as pd 
import numpy as np


In [5]:
train=pd.read_csv('train.csv')
#train.info()
target=train['Stay']
train=train.drop(['Stay'],axis=1)
test=pd.read_csv('test.csv')
print((train))

        case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0             1              8                  c                   3   
1             2              2                  c                   5   
2             3             10                  e                   1   
3             4             26                  b                   2   
4             5             26                  b                   2   
...         ...            ...                ...                 ...   
318433   318434              6                  a                   6   
318434   318435             24                  a                   1   
318435   318436              7                  a                   4   
318436   318437             11                  b                   2   
318437   318438             19                  a                   7   

       Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                         Z                

In [3]:
for i in train.columns:
    print(train[i].unique())

[     1      2      3 ... 318436 318437 318438]
[ 8  2 10 26 23 32  1 22 16  9  6 29 12  3 21 28 27 19  5 14 13 31 24 17
 25 15 11 30 18  4  7 20]
['c' 'e' 'b' 'a' 'f' 'd' 'g']
[ 3  5  1  2  6  9 10  4 11  7 13]
['Z' 'X' 'Y']
[ 3  2  1  4  6  5  7  8  9 10 12  0 11 20 14 21 13 24]
['radiotherapy' 'anesthesia' 'gynecology' 'TB & Chest disease' 'surgery']
['R' 'S' 'Q' 'P' 'T' 'U']
['F' 'E' 'D' 'B' 'A' 'C']
[ 2.  3.  4.  1. nan]
[ 31397  63418   8088 ... 125235  91081  21641]
[ 7.  8.  2.  5.  6.  3.  4.  1.  9. 14. nan 25. 15. 12. 10. 28. 24. 23.
 20. 11. 13. 21. 18. 16. 26. 27. 22. 19. 31. 34. 32. 30. 29. 37. 33. 35.
 36. 38.]
['Emergency' 'Trauma' 'Urgent']
['Extreme' 'Moderate' 'Minor']
[ 2  4  3  8  6  7 13  5  1 10 15 11 12  9 24 16 14 20  0 19 18 17 23 21
 32 30 22 25]
['51-60' '71-80' '31-40' '41-50' '81-90' '61-70' '21-30' '11-20' '0-10'
 '91-100']
[4911. 5954. 4745. ... 1937. 9439. 2349.]


In [4]:
train=train.drop(['Bed Grade'],axis=1)

In [5]:
#train['Age']=train['Age'].apply(lambda x:( int(x[0]) +int(x[2:4]) )/2 if x[0]== '0' else (int(x[0:2]) +int(x[3:5]))/2)


In [6]:
#train['Stay']=train['Stay'].apply(lambda x: '100' if x[0]== 'M' else x)


In [7]:
#train['Stay']=train['Stay'].apply(lambda x:( int(x[0]) +int(x[2:4]) )/2 if x[0]== '0' else (int(x[0:2]) +int(x[3:5]))/2)


In [8]:

a=train.columns
categorical=[i for i in a if train[i].dtype == 'O']


b=test.columns
categorical_test=[i for i in b if test[i].dtype == 'O']


numerical=[i for i in a if i not in categorical ]
#train=train.drop(['Bed Grade'],axis=1)
#train.shape


numerical_test=[i for i in a if i not in categorical_test ]
test=test.drop(['Bed Grade'],axis=1)
#test.shape

In [9]:
#train['Age'].unique()
train=pd.get_dummies(train,drop_first=True)
test=pd.get_dummies(test,drop_first=True)

In [10]:
#train.info()
#print(train)
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer(strategy='mean')
train_new = my_imputer.fit_transform(train)
test_new = my_imputer.fit_transform(test)

In [11]:
#from sklearn.preprocessing import OneHotEncoder
#one=OneHotEncoder()
#train_new=one.fit_transform(train)

In [12]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
target=lb.fit_transform(target)

In [13]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(train_new,target,test_size=0.4)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rc=RandomForestClassifier()
rc.fit(X_train,y_train)
predic=rc.predict(X_test)
print(accuracy_score(predic,y_test))